### ISSUE TITLE
Features

### ISSUE THREAD

**Issue by mithray** [SlavomirSlovenkai/MMO#25]
Two features that I think will be important are 

- A buy shop to buy and sell items(an archer class could sell unused sword, for example).
- Experience levels. Would it be difficult to add an arbitrary number of exp levels without duplicating templates? I certainly know how to do it with making more templates.

**Comment by LenaTheWolfess** [comment]
leveling: https://github.com/SlavomirSlovenkai/MMO/commit/907313ff5af0f64533351edf35ce4607974dac66

**Comment by LenaTheWolfess** [comment]
https://github.com/LenaTheWolfess/MMO/issues/37
