### ISSUE TITLE
abilities

### ISSUE THREAD

**Issue by LenaTheWolfess** [SlavomirSlovenkai/MMO#28]
dont know how but somehow ;)

**Comment by LenaTheWolfess** [comment]
step 1 https://github.com/SlavomirSlovenkai/MMO/commit/8aefc79c464a866390f8d1a88e4c5646a65a2468

**Comment by mithray** [comment]
Could you use the multiple attack feature from the main game ?

**Comment by LenaTheWolfess** [comment]
what do you mean by multiple attack feature ? I do not remember something like that.

**Comment by LenaTheWolfess** [comment]
Initial version of abilities works
