### ISSUE TITLE
gold resource

### ISSUE THREAD

**Issue by LenaTheWolfess** [SlavomirSlovenkai/MMO#29]

**Comment by LenaTheWolfess** [comment]
https://github.com/SlavomirSlovenkai/MMO/commit/907313ff5af0f64533351edf35ce4607974dac66

**Comment by mithray** [comment]
Is it necessary to have gold as a resource? Isn't it synonymous to weapons and armor in that it is held by the player? I think it's better to see them as categorically equivalent. 

If this is so, you can hold gold, and hold weapons, all is contained in your inventory, there is no need for any concept of "resources" at all. Alternately, you consider all weapons as resources, and you can use the market barter system from the main game(most likely with an adapted UI) when creating a shop.

**Comment by LenaTheWolfess** [comment]
no i cant.
i treat each item as unique entity which would not work for gold for obvious reason
Looks like you need a bit different system for your mod, but should not be that hard to tweak this one.
