### ISSUE TITLE
Better visible items on ground

### ISSUE THREAD

**Issue by LenaTheWolfess** [SlavomirSlovenkai/MMO#8]
Hard to click and hard to spot.
Particles ?
Hovering indicator above ?
Glowing?

**Comment by mithray** [comment]
We could temporarily fix this by replacing the sword actor file with say, a rack of swords. Would be cool ta have a glowing circle underneath, and the equipment gently turns in mid air. Unless you think that's a little comical :-) . I like it.

**Comment by LenaTheWolfess** [comment]
they have star always visible now
